### ISSUE TITLE
Class visibility

### ISSUE THREAD

**Issue by ErwanLT** [ErwanLT/JasperClient#5]
To implement the client, the main class and some methode need to be public and not package private.
Change the visibility of those.

**Class visibility :**
change the visibility of **JasperClient** from _abstract class_ to _public abstract class_

**methode visibility :**
In **JasperClient** make
- simpleParamters
- listParamters
- arrayParameters

_public abstract void_ instead of just _abstract void_

**Comment by ParthasarathiMahana** [comment]
Hi @ErwanLT I would like to contribute to this Issue, can we discuss more on it??

**Comment by ErwanLT** [comment]
@ParthasarathiMahana I can assign it to you if you want.
I will edit the original content of the issue to describe more precisely what to do.

**Comment by ParthasarathiMahana** [comment]
@ErwanLT That is great , thank you.
